version: "3.8"
services:
  db:
    image: postgres:16.2-alpine
    container_name: postgres-cont
    restart: always
    env_file:
      - path: ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
