definitions:
  models.Gate:
    properties:
      floor_number:
        type: integer
      gate_number:
        type: integer
      id:
        type: string
    type: object
info:
  contact: {}
paths:
  /gate/{id}:
    get:
      description: Retrieve a gate by its ID
      operationId: get-gate-by-id
      parameters:
      - description: Gate ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
        "400":
          description: Gate not found
      summary: Get gate by ID
      tags:
      - gate
    put:
      consumes:
      - application/json
      description: Update gate of given id
      operationId: update-gate
      parameters:
<<<<<<< HEAD
=======
      - description: Updated gate object
        in: body
        name: gate
        required: true
        schema:
          $ref: '#/definitions/models.Gate'
>>>>>>> 844c91c ([Shaz|Madhavan] added body annotation)
      - description: Gate ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Gate updated sucessfully
        "400":
          description: Gate not found
      summary: Update ga
      tags:
      - gate
  /gates:
    get:
      description: get all the gate details
      operationId: get-all-gate
      parameters:
      - description: Page number (default = 0)
        in: query
        name: page
        type: integer
      - description: filter by floor (default = all floor)
        in: query
        name: floor
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
        "500":
          description: Internal server error
      summary: Get all gates
      tags:
      - gate
swagger: "2.0"
