name: Build and test from latest commit on master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_test:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build all on ${{matrix.os}}
        run: make all

      # Add Snyk integration
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk security scan
        continue-on-error: true
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --all-projects
