name: Build and test from latest commit on master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_test:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build all on ${{matrix.os}}
        run: make all

  snyk-scan:
        name: Snyk scan on Ubuntu
        runs-on: ubuntu-latest

        steps:

          - name: Set up Go
            uses: actions/setup-go@v2
            with:
              go-version: 1.22.1
            id: go

          - name: Checkout code
            uses: actions/checkout@v2

          - name: Install curl
            run: sudo apt-get update && sudo apt-get install -y curl

          - name: Install Homebrew
            run: |
                sudo apt-get update
                sudo apt-get install -y curl
                /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          - name: Install Snyk CLI
            run: brew install snyk

          - name: Run Snyk Test
            run: snyk test --all-projects

          - name: Display Snyk Report Link
            run: echo "Snyk scan completed! View the report at https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2-6531285"
